[build]
  base = "frontend/"
  publish = ".next"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock --no-audit"
  # Explicitly set Go version to avoid installation issues
  GO_VERSION = ""
  # Skip mise (the problematic tool)
  MISE_GLOBAL_CONFIG_FILE = "/dev/null"
  # Environment variable to force re-compilation of binary modules
  NPM_FORCE_RESOLUTIONS = "true"
  
# Try to bypass cache issues
[build.processing]
  skip_processing = true

# Force clear cache for builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add a build plugin to clear cache
[[plugins]]
  package = "netlify-plugin-cache-busting"

# Use our custom cache-clearing plugin
[[plugins]]
  package = "./netlify-plugin-cache-clear.js"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 