[build]
  base = "frontend/"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock --no-audit"
  # Explicitly disable Python
  PYTHON_VERSION = "off"
  
# Try to bypass cache issues
[build.processing]
  skip_processing = true

# Force clear cache for builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add a build plugin to clear cache
[[plugins]]
  package = "netlify-plugin-cache-busting"

# Use our custom cache-clearing plugin
[[plugins]]
  package = "./netlify-plugin-cache-clear.js"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 