[build]
  base = "frontend/"
  publish = ".next"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  # Node configuration
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-package-lock --no-audit --prefer-offline --no-fund"
  
  # Python configuration - set to a specific working version
  PYTHON_VERSION = "3.9.18"
  
  # Disable Go
  GO_VERSION = ""
  
  # Eliminate the use of mise
  MISE_DISABLE = "1"
  MISE_GLOBAL_CONFIG_FILE = "/dev/null"
  
  # Force binary modules to rebuild
  NPM_FORCE_RESOLUTIONS = "true"
  
  # Skip Next.js plugin since we're handling it manually
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
# Try to bypass cache issues
[build.processing]
  skip_processing = true

# Use only essential plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 