[build]
  base = "frontend/"
  publish = "out"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  # Node configuration
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-package-lock --no-audit --prefer-offline --no-fund --legacy-peer-deps"
  
  # Set to a stable, known Python version that definitely exists in Netlify
  PYTHON_VERSION = "3.10"
  PYTHON_FLAGS = "-m pip install --upgrade pip"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  
  # Disable Go
  GO_VERSION = ""
  
  # Eliminate the use of mise
  MISE_DISABLE = "1"
  MISE_GLOBAL_CONFIG_FILE = "/dev/null"
  
  # Force binary modules to rebuild
  NPM_FORCE_RESOLUTIONS = "true"
  
  # Skip Next.js plugin since we're handling it manually
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
  # Set NODE_ENV
  NODE_ENV = "production"
  
  # Add build flags for Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Add cache control
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  
  # Enable debug output
  NETLIFY_BUILD_DEBUG = "true"

# Try to bypass cache issues
[build.processing]
  skip_processing = true

# Handle 404s correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Proper API redirects if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 