[build]
  base = "frontend/"
  publish = "out"
  command = "npm ci && npm run build && mkdir -p out && find .next -type f -name '*.html' -exec cp {} out/ \\; && mkdir -p out/_next && cp -r .next/static out/_next/ || true"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  # Disable everything else
  PYTHON_VERSION = "disabled"
  SKIP_MISE = "true"
  NETLIFY_USE_YARN = "false"

# Try to bypass cache issues
[build.processing]
  skip_processing = true

# Handle 404s correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper API redirects if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 