# Basic build settings
[build]
  base = \
frontend/\
  publish = \
out\
  command = "npm install --no-optional && npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
