[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-nextjs" 