[build]
  base = "frontend"
  command = "bash ./netlify-build.sh"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PYTHON_ENABLE = "0"

[[plugins]]
  package = "./frontend/netlify-plugin-cache-clear" 