[build]
  base = "frontend"
  command = "npm run build && npm run postbuild"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle Next.js routing
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Remove all plugins to avoid any Python dependencies
# [[plugins]]
#  package = "./frontend/netlify-plugin-cache-clear" 