[build]
  base = "frontend"
  command = "bash ./netlify-build.sh"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PYTHON_VERSION = "3.8"
  NETLIFY_USE_MISE = "false"

# Remove all plugins to avoid any Python dependencies
# [[plugins]]
#  package = "./frontend/netlify-plugin-cache-clear" 