# fly.toml app configuration file generated for dogid-backend on 2025-02-28T21:28:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dogid-backend'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
